### PR TITLE
Added "--recursive" to "git clone" command.

### PR DESCRIPTION
**Pull request by NeuralMiner**
Added `--recursive` to `git clone` command to resolve issue with `docker-compose up -d` (#9).

### CODE REVIEW

**Comment by marius311** [comment]
Thanks. I'd actually prefer to keep the default instructions without `--recursive ` because first time users don't need the submodules since they're not building the images, and downloading the BOINC submodule is a fairly large download that might take a while. But you're right, it should be documented somewhere that once you start building the images you need the submodules.

**Comment by NeuralMiner** [comment]
Hmm. I did a first time deploy on a fresh VM just now and needed `--recursive` or I received the "/bin/sh: 1: ./_autosetup: not found" error.

**Comment by marius311** [comment]
Ahh I see, for some reason I thought `docker-compose up` pulled missing images, instead it builds them then fails with the error you guys mentioned. 

I'm going to add `docker-compose pull` to the basic instructions, and I'll add a note saying you need the submodules for custom builds.

**Comment by marius311** [comment]
Fixed with https://github.com/marius311/boinc-server-docker/commit/f19b76858eee55ac1521fc16e1a95dee2196ff6d

**Pull request closed without merging**
